# Generated by Django 2.0 on 2017-12-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='pic',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='游玩图片'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='游玩图片'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='游玩图片'),
        ),
    ]
