# Generated by Django 2.0 on 2017-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='pic',
            field=models.CharField(max_length=100, null=True, verbose_name='游玩图片'),
        ),
    ]
