# Generated by Django 2.0 on 2017-12-25 11:53

import datetime
from django.db import migrations, models
import evaluationapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0002_auto_20171225_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to=evaluationapp.models.upload_to, verbose_name='游玩图片'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=evaluationapp.models.upload_to, verbose_name='游玩图片'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=evaluationapp.models.upload_to, verbose_name='游玩图片'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='时间'),
        ),
    ]
