# Generated by Django 2.0 on 2017-12-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('evaluationapp', '0003_auto_20171225_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='likes',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='usr_like',
            field=models.ManyToManyField(related_name='usr_like_set', to='userapp.User'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='userapp.User'),
        ),
    ]
