# Generated by Django 2.0 on 2018-01-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0004_auto_20171229_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_set', to='userapp.User'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='usr_like',
            field=models.ManyToManyField(related_name='evaluation_like_set', to='userapp.User'),
        ),
    ]
