# Generated by Django 2.0 on 2018-01-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0007_auto_20180104_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='hotspot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotspotapp.HotSpot'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='rate',
            field=models.CharField(default=0, max_length=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_set', to='userapp.User'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='usr_like',
            field=models.ManyToManyField(null=True, related_name='evaluation_like_set', to='userapp.User'),
        ),
    ]
