# Generated by Django 2.0 on 2018-01-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0008_auto_20180104_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='price',
            field=models.CharField(max_length=20, null=True, verbose_name='消费'),
        ),
    ]
