# Generated by Django 2.0 on 2017-12-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('birday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, null=True, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=100, null=True, verbose_name='地址')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('pic', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像')),
                ('introduction', models.CharField(default='', max_length=200, null=True, verbose_name='简介')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('credit', models.IntegerField(default=100, verbose_name='信用值')),
                ('follower', models.ManyToManyField(related_name='_user_follower_+', to='userapp.User')),
                ('following', models.ManyToManyField(related_name='_user_following_+', to='userapp.User')),
            ],
        ),
    ]
