# Generated by Django 2.0 on 2017-12-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activityapp', '0001_initial'),
        ('hotspotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('password', models.CharField(default='123456', max_length=100, verbose_name='密码')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(max_length=6, null=True, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=100, null=True, verbose_name='地址')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='电话')),
                ('pic', models.ImageField(default='pic/default.png', null=True, upload_to='', verbose_name='头像')),
                ('introduction', models.CharField(default='', max_length=200, null=True, verbose_name='简介')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='邮箱')),
                ('credit', models.IntegerField(default=100, null=True, verbose_name='信用值')),
                ('access_token', models.CharField(default='', max_length=100, null=True, unique=True, verbose_name='验证头')),
                ('favour_activity', models.ManyToManyField(to='activityapp.Activity')),
                ('favour_hotspot', models.ManyToManyField(to='hotspotapp.HotSpot')),
                ('follower', models.ManyToManyField(related_name='_user_follower_+', to='userapp.User')),
                ('following', models.ManyToManyField(related_name='_user_following_+', to='userapp.User')),
            ],
        ),
    ]
