# Generated by Django 2.0 on 2017-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20171214_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=6, null=True, verbose_name='性别'),
        ),
    ]
