# Generated by Django 2.0 on 2017-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20171214_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birday',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='default.png', null=True, upload_to='', verbose_name='头像'),
        ),
    ]
