# Generated by Django 2.0 on 2017-12-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0009_auto_20171219_1033'),
        ('activityapp', '0002_auto_20171219_1430'),
        ('userapp', '0006_auto_20171217_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favour_activity',
            field=models.ManyToManyField(to='activityapp.Activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='favour_hotspot',
            field=models.ManyToManyField(to='hotspotapp.HotSpot'),
        ),
    ]
