# Generated by Django 2.0 on 2017-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20171219_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favour_activity',
            field=models.ManyToManyField(to='activityapp.Activity'),
        ),
    ]
