# Generated by Django 2.0 on 2017-12-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotspotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动标题')),
                ('subject', models.CharField(max_length=50, verbose_name='活动主题')),
                ('time', models.DateTimeField(verbose_name='举办时间')),
                ('type', models.CharField(max_length=50, verbose_name='活动类型')),
                ('introduction', models.CharField(max_length=200, verbose_name='活动简介')),
                ('person', models.IntegerField(null=True, verbose_name='限定人数')),
                ('telephone', models.CharField(max_length=200, verbose_name='联系方式')),
                ('website', models.CharField(max_length=500, verbose_name='活动网址')),
                ('pic', models.ImageField(upload_to='', verbose_name='活动图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='费用')),
                ('host_user', models.CharField(max_length=50, null=True, verbose_name='活动发起人账号')),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspotapp.HotSpot')),
            ],
        ),
    ]
