# Generated by Django 2.0 on 2017-12-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='host_user',
            field=models.CharField(max_length=50, null=True, verbose_name='活动发起人账号'),
        ),
    ]
