# Generated by Django 2.0 on 2017-12-21 07:05

import activityapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='pic',
        ),
        migrations.AddField(
            model_name='activity',
            name='pic1',
            field=models.ImageField(null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片1'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pic2',
            field=models.ImageField(null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片3'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pic3',
            field=models.ImageField(null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='introduction',
            field=models.TextField(max_length=200, verbose_name='活动简介'),
        ),
    ]
