# Generated by Django 2.0 on 2017-12-21 07:06

import activityapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0002_auto_20171221_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片3'),
        ),
    ]
