# Generated by Django 2.0 on 2017-12-21 07:08

import activityapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0003_auto_20171221_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='host_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='活动发起人账号'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='person',
            field=models.IntegerField(blank=True, null=True, verbose_name='限定人数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='website',
            field=models.CharField(blank=True, max_length=500, verbose_name='活动网址'),
        ),
    ]
