# Generated by Django 2.0 on 2017-12-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0004_auto_20171221_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hotspot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotspotapp.HotSpot'),
        ),
    ]
