# Generated by Django 2.0 on 2017-12-21 08:00

import activityapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0006_auto_20171221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pic1',
            field=models.ImageField(default='activity/default.png', null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片1'),
        ),
    ]
