# Generated by Django 2.0 on 2017-12-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0008_auto_20171225_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='englishname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='活动英文名'),
        ),
    ]
