# Generated by Django 2.0 on 2017-12-27 06:00

import activityapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0009_activity_englishname'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to=activityapp.models.upload_to, verbose_name='活动图片3'),
        ),
    ]
