# Generated by Django 2.0 on 2017-12-20 12:52

from django.db import migrations, models
import hotspotapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='地点名称')),
                ('englishname', models.CharField(max_length=100, null=True, verbose_name='英文名称')),
                ('word', models.CharField(blank=True, max_length=100, null=True, verbose_name='一句话描述')),
                ('worktime', models.CharField(max_length=100, null=True, verbose_name='营业时间')),
                ('price', models.CharField(max_length=30, null=True, verbose_name='人均消费')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在城市')),
                ('pic1', models.ImageField(default='', upload_to=hotspotapp.models.upload_to, verbose_name='图片一')),
                ('pic1_text', models.CharField(default='', max_length=200, null=True, verbose_name='图一解说')),
                ('pic2', models.ImageField(default='', upload_to=hotspotapp.models.upload_to, verbose_name='图二')),
                ('pic2_text', models.CharField(default='', max_length=200, null=True, verbose_name='图二解说')),
                ('pic3', models.ImageField(default='', upload_to=hotspotapp.models.upload_to, verbose_name='图片三')),
                ('pic3_text', models.CharField(default='', max_length=200, null=True, verbose_name='图三解说')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('url', models.CharField(default='', max_length=200, null=True, verbose_name='网址')),
                ('telephone', models.CharField(max_length=30, null=True, verbose_name='联系电话')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('arrived', models.IntegerField(default=0, verbose_name='签到数')),
            ],
        ),
    ]
