# Generated by Django 2.0 on 2017-12-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('word', models.CharField(blank=True, max_length=100, null=True, verbose_name='一句话描述')),
                ('worktime', models.CharField(max_length=100, null=True, verbose_name='营业时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='人均消费')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在城市')),
                ('pic', models.ImageField(upload_to='', verbose_name='图片')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('arrived', models.IntegerField(default=0, verbose_name='签到数')),
            ],
        ),
    ]
