# Generated by Django 2.0 on 2017-12-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='pic1_text',
            field=models.CharField(default='', max_length=200, verbose_name='图一解说'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='pic2_text',
            field=models.CharField(default='', max_length=200, verbose_name='图二解说'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='pic3_text',
            field=models.CharField(default='', max_length=200, verbose_name='图三解说'),
        ),
    ]
