# Generated by Django 2.0 on 2017-12-28 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区域')),
                ('englishName', models.CharField(max_length=100, verbose_name='英文名字')),
                ('city', models.CharField(max_length=50, verbose_name='所在城市')),
                ('introduction', models.CharField(max_length=500, verbose_name='介绍')),
                ('pic', models.ImageField(max_length=50, upload_to='', verbose_name='图片')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='city',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotspotapp.District'),
        ),
    ]
