# Generated by Django 2.0 on 2017-12-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0002_auto_20171228_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='introduction',
            field=models.TextField(max_length=500, verbose_name='介绍'),
        ),
    ]
