# Generated by Django 2.0 on 2017-12-18 06:33

import androidbackend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0003_auto_20171218_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='pic',
            field=models.ImageField(upload_to=androidbackend.utils.upload_to, verbose_name='图片'),
        ),
    ]
