# Generated by Django 2.0 on 2017-12-28 03:23

from django.db import migrations, models
import hotspotapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0004_auto_20171228_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='pic',
            field=models.ImageField(max_length=50, upload_to=hotspotapp.models.d_upload_to, verbose_name='图片'),
        ),
    ]
