# Generated by Django 2.0 on 2017-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0004_auto_20171218_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='url',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='网址'),
        ),
    ]
