# Generated by Django 2.0 on 2018-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0005_auto_20171228_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='latitude',
            field=models.BigIntegerField(null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='longitude',
            field=models.BigIntegerField(null=True, verbose_name='经度'),
        ),
    ]
