# Generated by Django 2.0 on 2017-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0005_hotspot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='telephone',
            field=models.CharField(max_length=30, null=True, verbose_name='联系电话'),
        ),
    ]
