# Generated by Django 2.0 on 2018-01-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0006_auto_20180103_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.BigIntegerField(null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.BigIntegerField(null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='latitude',
            field=models.CharField(max_length=20, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='longitude',
            field=models.CharField(max_length=20, null=True, verbose_name='经度'),
        ),
    ]
