# Generated by Django 2.0 on 2017-12-19 01:50

import androidbackend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0006_hotspot_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='pic',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='pic1',
            field=models.ImageField(default='', upload_to=androidbackend.utils.upload_to, verbose_name='图片一'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='pic2',
            field=models.ImageField(default='', upload_to=androidbackend.utils.upload_to, verbose_name='图二'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='pic3',
            field=models.ImageField(default='', upload_to=androidbackend.utils.upload_to, verbose_name='图片三'),
        ),
    ]
