# Generated by Django 2.0 on 2017-12-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0007_auto_20171219_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='englishname',
            field=models.CharField(max_length=100, null=True, verbose_name='英文名称'),
        ),
    ]
