# Generated by Django 2.0 on 2018-01-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0008_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='latitude',
            field=models.CharField(max_length=20, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='district',
            name='longitude',
            field=models.CharField(max_length=20, null=True, verbose_name='经度'),
        ),
    ]
