# Generated by Django 2.0 on 2017-12-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0008_hotspot_englishname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='price',
            field=models.CharField(max_length=30, null=True, verbose_name='人均消费'),
        ),
    ]
