# Generated by Django 2.0 on 2018-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0009_auto_20180103_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='时间'),
        ),
    ]
