# Generated by Django 2.0 on 2018-01-08 06:58

from django.db import migrations, models
import hotspotapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0011_auto_20180105_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('pic', models.ImageField(upload_to=hotspotapp.models.c_upload_to, verbose_name='图片')),
            ],
        ),
    ]
