# Generated by Django 2.0 on 2018-01-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0013_district_city_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='englishname',
            field=models.CharField(max_length=100, null=True, verbose_name='英文名称'),
        ),
    ]
